language: node_js
node_js:
  - 8
  - 9
cache:
  directories:
    - node_modules
    - client/node_modules
    - server/node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"
  - cd client
install:
  - yarn --focus
script:
  - yarn build
  - yarn test